### ISSUE TITLE
Panic when accessing stats

### ISSUE THREAD

**Issue by utdrmac** [thelastguardian/tplinkexporter#1]
```
$ docker run -it -p 9717:9717 thelastguardian/tplinkexporter --host 10.10.10.2 --username admin --password admin1
Unable to find image 'thelastguardian/tplinkexporter:latest' locally
latest: Pulling from thelastguardian/tplinkexporter
2487b8433001: Pull complete
b637faead5d8: Pull complete
Digest: sha256:83aca539718e1333e1bd781bd90f35832036ce2b8d317ae6464feb25e7c818de
Status: Downloaded newer image for thelastguardian/tplinkexporter:latest
INFO[0000] Beginning to serve on port :9717              source="main.go:27"
panic: runtime error: index out of range [1] with length 0

goroutine 24 [running]:
github.com/thelastguardian/tplinkexporter/clients.(*TPLINKSwitch).GetPortStats(0xc00008ddd0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/clients/tl_sg108e_client.go:65 +0xd42
github.com/thelastguardian/tplinkexporter/collectors.(*TrafficCollector).Collect(0xc0001221e0, 0xc0000b0d20)
	/build/collectors/portinfo.go:81 +0x4c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:454 +0x57d
```

**Comment by utdrmac** [comment]
Seems I had the wrong password. Feature request would be to validate UN/PW to the switch before starting? Or maybe display error at /metrics ?
